<?php 
return array(  
	'error_unknown' => 'Something went wrong',
	'save_changes' => 'Save Changes',
	'general_successful' => 'Successful',
	'access_login' => 'Log In',
	'access_signup' => 'Sign Up',
	'access_logout' => 'Logout',
	'access_error1' => 'Incorrect username or password',
	'access_forgot' => 'Forgot password?',
	'access_noaccount' => 'Don\'t have an account yet?',
	'access_haveaccount' => 'Already have an account?',
	'signup_emailexists' => 'Account with this email already exists',
	'signup_usernameexists' => 'Account with this username already exists',
	'signup_success' => 'Welcome, your registration was a success! Check your email for confirmation.',
	'forgot_title' => 'Forgot Your Password?',
	'forgot_desc' => 'Happens all the time. Enter the email address associated with your account and we will send you a new password.',
	'forgot_action' => 'Reset Password',
	'forgot_emailnoexists' => 'There is no account associated with this email address.',
	'forgot_emailsend' => 'An email with a password reset code was sent to you',
	'user_edit_oldpassword' => 'Old password doesn\'t match',
	'user_edit_passnomatch' => 'Password confirmation must be the same as password',
	'user_edit_invalidpass' => 'Password must be at least six characters long',
	'user_edit_successful' => 'Thank you. Your Profile has been updated.',
	'user_edit_photoerror' => 'Something went wrong, try again please.',
	'project_successful' => 'Thank you. The project has been updated.',
	'subproject_successful' => 'Thank you. The competition has been updated.',
	'data_name' => 'Name',
	'data_username' => 'Username',
	'data_email' => 'Email',
	'data_password' => 'Password',
	'bad_email_format' => 'Please use a valid email format',
	'bad_username_format' => 'Please enter a valid username',
	'bad_password_lenght' => 'Your password must contain at least 6 characters',
	'bad_password_format' => 'Your password must contain at least 6  to 20 characters',
);
?>