<?php 
return array(  
	'error_unknown' => 'Algo salió mal',
	'save_changes' => 'Guardar cambios',
	'general_successful' => 'Los cambios fueron realizados con éxito',
	'error_no_access' => 'Oops! ¿Qué es lo que estás buscando aquí?',
	'error_no_apikey' => 'Api key inválido.',
	'search_no_results' => 'No existen resultados para esa búsqueda.',
	'access_login' => 'Inicia sesión',
	'access_login_or' => 'O accede con',
	'access_signup' => 'Regístrate',
	'access_logout' => 'Cerrar sesión',
	'access_error1' => 'Nombre de usuario o contraseña incorrectos',
	'access_forgot' => '¿Olvidaste tu contraseña?',
	'access_noaccount' => '¿Aún no tienes una cuenta?',
	'access_haveaccount' => '¿Ya tienes una cuenta?',
	'access_ok' => 'Bienvenido otra vez.',
	'signup_emailexists' => 'Este correo electrónico ya está siendo utilizado por otra cuenta.',
	'signup_usernameexists' => 'El nombre de usuario ya está siendo utilizado.',
	'signup_success' => '¡Excelente, ya estás registrado!',
	'forgot_title' => '¿Olvidaste tu contraseña?',
	'forgot_desc' => 'Sucede todo el tiempo. Ingresa tu correo electrónico y te ayudaremos.',
	'forgot_action' => 'Restablecer contraseña',
	'forgot_emailnoexists' => 'No existe una cuenta asociada con este correo electrónico.',
	'forgot_emailsend' => 'Se te ha enviado un correo para restablecer la contraseña.',
	'user_edit_oldpassword' => 'Tu antigua contraseña no coincide.',
	'user_edit_passnomatch' => 'La confirmación de la contraseña no coincide: verifícalo e intenta de nuevo.',
	'user_edit_invalidpass' => 'Tu contraseña debe tener, al menos, seis caracteres.',
	'user_edit_successful' => 'Gracias. Tu perfil fue actualizado.',
	'user_edit_photoerror' => 'Tuvimos un problema. Intenta cargar la imagen de nuevo.',
	'data_name' => 'Nombre',
	'data_username' => 'Nombre de usuario',
	'data_email' => 'Correo electrónico',
	'data_emailoruser' => 'Correo electrónico o nombre de usuario',
	'data_password' => 'Contraseña',
	'data_passwordretype' => 'Confirmar Contraseña',
	'bad_email_format' => 'Por favor ingresa un correo electrónico válido.',
	'bad_username_format' => 'Por favor verifica tu nombre de usuario',
	'bad_password_lenght' => 'Tu contraseña debe tener, al menos, seis caracteres.',
	'bad_password_format' => 'Tu contraseña debe tener de seis a veinte caracteres válidos.',
	'form_info' => 'Utiliza ‘<b>#</b>’ para agregar temas o ‘<b>@</b>’ para etiquetar usuarios.'
);
?>